### ISSUE TITLE
No hourly tariffs on net_operator "Veksel"

### ISSUE THREAD

**Issue by MicBehrens** [MTrab/energidataservice#215]
### Environment:
- Home Assistant version: 2022.12.9
- Energidatastyrelsen version: 1.1.0
- Operation system: HAOS

## Configuration
- Country: Denmark
- Region: West of the great belt
- Show in cents: No
- Number of decimals: 3
- Price calculated in: kWh
- Template for additional costs: {{0.0375|float}}
- Automatically fetch tariff data: Yes
- Net operator: Veksel

## Describe the bug
No hourly tariffs are being found for net operator Veksel, the "tariff"-object is empty. Have tried other net operators, which worked flawlessly.

Attributes:
```
state_class: measurement
unit_of_measurement: DKK/kWh
device_class: monetary
icon: mdi:flash
friendly_name: Energi Data Service (Sommerhus)
current_price: 0.986
unit: kWh
currency: DKK
region: West of the great belt
region_code: DK1
tomorrow_valid: true
next_data_update: 13:32:05
today: 0.5, 0.355, 0.281, 0.222, 0.228, 0.432, 0.706, 1.014, 1.182, 1.132, 1.079, 0.986, 0.908, 0.85, 0.881, 0.939, 0.99, 1.098, 1.098, 1.088, 0.986, 0.912, 0.908, 0.832
tomorrow: 0.436, 0.519, 0.612, 0.58, 0.575, 0.575, 0.616, 0.693, 0.695, 0.726, 0.817, 0.806, 0.805, 0.78, 0.589, 0.382, 0.281, 0.3, 0.324, 0.26, 0.281, 0.281, 0.252, 0.245
raw_today: 
- hour: '2023-01-13T00:00:00+01:00'
  price: 0.5
- hour: '2023-01-13T01:00:00+01:00'
  price: 0.355
- hour: '2023-01-13T02:00:00+01:00'
  price: 0.281
- hour: '2023-01-13T03:00:00+01:00'
  price: 0.222
- hour: '2023-01-13T04:00:00+01:00'
  price: 0.228
- hour: '2023-01-13T05:00:00+01:00'
  price: 0.432
- hour: '2023-01-13T06:00:00+01:00'
  price: 0.706
- hour: '2023-01-13T07:00:00+01:00'
  price: 1.014
- hour: '2023-01-13T08:00:00+01:00'
  price: 1.182
- hour: '2023-01-13T09:00:00+01:00'
  price: 1.132
- hour: '2023-01-13T10:00:00+01:00'
  price: 1.079
- hour: '2023-01-13T11:00:00+01:00'
  price: 0.986
- hour: '2023-01-13T12:00:00+01:00'
  price: 0.908
- hour: '2023-01-13T13:00:00+01:00'
  price: 0.85
- hour: '2023-01-13T14:00:00+01:00'
  price: 0.881
- hour: '2023-01-13T15:00:00+01:00'
  price: 0.939
- hour: '2023-01-13T16:00:00+01:00'
  price: 0.99
- hour: '2023-01-13T17:00:00+01:00'
  price: 1.098
- hour: '2023-01-13T18:00:00+01:00'
  price: 1.098
- hour: '2023-01-13T19:00:00+01:00'
  price: 1.088
- hour: '2023-01-13T20:00:00+01:00'
  price: 0.986
- hour: '2023-01-13T21:00:00+01:00'
  price: 0.912
- hour: '2023-01-13T22:00:00+01:00'
  price: 0.908
- hour: '2023-01-13T23:00:00+01:00'
  price: 0.832

raw_tomorrow: 
- hour: '2023-01-14T00:00:00+01:00'
  price: 0.436
- hour: '2023-01-14T01:00:00+01:00'
  price: 0.519
- hour: '2023-01-14T02:00:00+01:00'
  price: 0.612
- hour: '2023-01-14T03:00:00+01:00'
  price: 0.58
- hour: '2023-01-14T04:00:00+01:00'
  price: 0.575
- hour: '2023-01-14T05:00:00+01:00'
  price: 0.575
- hour: '2023-01-14T06:00:00+01:00'
  price: 0.616
- hour: '2023-01-14T07:00:00+01:00'
  price: 0.693
- hour: '2023-01-14T08:00:00+01:00'
  price: 0.695
- hour: '2023-01-14T09:00:00+01:00'
  price: 0.726
- hour: '2023-01-14T10:00:00+01:00'
  price: 0.817
- hour: '2023-01-14T11:00:00+01:00'
  price: 0.806
- hour: '2023-01-14T12:00:00+01:00'
  price: 0.805
- hour: '2023-01-14T13:00:00+01:00'
  price: 0.78
- hour: '2023-01-14T14:00:00+01:00'
  price: 0.589
- hour: '2023-01-14T15:00:00+01:00'
  price: 0.382
- hour: '2023-01-14T16:00:00+01:00'
  price: 0.281
- hour: '2023-01-14T17:00:00+01:00'
  price: 0.3
- hour: '2023-01-14T18:00:00+01:00'
  price: 0.324
- hour: '2023-01-14T19:00:00+01:00'
  price: 0.26
- hour: '2023-01-14T20:00:00+01:00'
  price: 0.281
- hour: '2023-01-14T21:00:00+01:00'
  price: 0.281
- hour: '2023-01-14T22:00:00+01:00'
  price: 0.252
- hour: '2023-01-14T23:00:00+01:00'
  price: 0.245

today_min: 
hour: '2023-01-13T03:00:00+01:00'
price: 0.222

today_max: 
hour: '2023-01-13T08:00:00+01:00'
price: 1.182

today_mean: 0.817
tomorrow_min: 
hour: '2023-01-14T23:00:00+01:00'
price: 0.245

tomorrow_max: 
hour: '2023-01-14T10:00:00+01:00'
price: 0.817

tomorrow_mean: 0.518
attribution: Data sourced from Energi Data Service
net_operator: Veksel
tariffs: 
additional_tariffs:
  transmissions_net_tarif: 0.058
  system_tarif: 0.054
  el_afgift: 0.008
tariffs: {}
```

## Debug log

```
This error originated from a custom integration.

Logger: custom_components.energidataservice.sensor
Source: custom_components/energidataservice/sensor.py:627
Integration: Energi Data Service (documentation, issues)
First occurred: 21:08:21 (48 occurrences)
Last logged: 21:08:21

Error adding tariffs for 2023-01-14 19:00:00+01:00, no valid tariffs was found!
Error adding tariffs for 2023-01-14 20:00:00+01:00, no valid tariffs was found!
Error adding tariffs for 2023-01-14 21:00:00+01:00, no valid tariffs was found!
Error adding tariffs for 2023-01-14 22:00:00+01:00, no valid tariffs was found!
Error adding tariffs for 2023-01-14 23:00:00+01:00, no valid tariffs was found!
```

## Diganostics data from the device

```

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.12.9",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Copenhagen",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "energidataservice": {
      "version": "1.1.0",
      "requirements": [
        "CurrencyConverter==0.17.4"
      ]
    },
    "hacs": {
      "version": "1.29.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "after_dependencies": [
      "http"
    ],
    "codeowners": [
      "@MTrab"
    ],
    "config_flow": true,
    "documentation": "https://github.com/MTrab/energidataservice/blob/master/README.md",
    "domain": "energidataservice",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/MTrab/energidataservice/issues",
    "name": "Energi Data Service",
    "requirements": [
      "CurrencyConverter==0.17.4"
    ],
    "version": "1.1.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "9398babf189afc6b695d0a1b44acb522",
      "version": 1,
      "domain": "energidataservice",
      "title": "Energi Data Service (Sommerhus)",
      "data": {
        "name": "Energi Data Service (Sommerhus)"
      },
      "options": {
        "tariff_charge_owner": "Veksel",
        "enable_forecast": false,
        "enable_tariffs": true,
        "area": "West of the great belt",
        "vat": true,
        "in_cent": false,
        "decimals": 3,
        "pricetype": "kWh",
        "cost_template": "{{0.0375|float}}",
        "name": "Energi Data Service (Sommerhus)",
        "country": "Denmark"
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "today": [
      [
        0.5,
        "2023-01-13T00:00:00+01:00"
      ],
      [
        0.355,
        "2023-01-13T01:00:00+01:00"
      ],
      [
        0.281,
        "2023-01-13T02:00:00+01:00"
      ],
      [
        0.222,
        "2023-01-13T03:00:00+01:00"
      ],
      [
        0.228,
        "2023-01-13T04:00:00+01:00"
      ],
      [
        0.432,
        "2023-01-13T05:00:00+01:00"
      ],
      [
        0.706,
        "2023-01-13T06:00:00+01:00"
      ],
      [
        1.014,
        "2023-01-13T07:00:00+01:00"
      ],
      [
        1.182,
        "2023-01-13T08:00:00+01:00"
      ],
      [
        1.132,
        "2023-01-13T09:00:00+01:00"
      ],
      [
        1.079,
        "2023-01-13T10:00:00+01:00"
      ],
      [
        0.986,
        "2023-01-13T11:00:00+01:00"
      ],
      [
        0.908,
        "2023-01-13T12:00:00+01:00"
      ],
      [
        0.85,
        "2023-01-13T13:00:00+01:00"
      ],
      [
        0.881,
        "2023-01-13T14:00:00+01:00"
      ],
      [
        0.939,
        "2023-01-13T15:00:00+01:00"
      ],
      [
        0.99,
        "2023-01-13T16:00:00+01:00"
      ],
      [
        1.098,
        "2023-01-13T17:00:00+01:00"
      ],
      [
        1.098,
        "2023-01-13T18:00:00+01:00"
      ],
      [
        1.088,
        "2023-01-13T19:00:00+01:00"
      ],
      [
        0.986,
        "2023-01-13T20:00:00+01:00"
      ],
      [
        0.912,
        "2023-01-13T21:00:00+01:00"
      ],
      [
        0.908,
        "2023-01-13T22:00:00+01:00"
      ],
      [
        0.832,
        "2023-01-13T23:00:00+01:00"
      ]
    ],
    "today_calculated": true,
    "api_today": [
      [
        32.639999,
        "2023-01-13T00:00:00+01:00"
      ],
      [
        16.99,
        "2023-01-13T01:00:00+01:00"
      ],
      [
        9.0,
        "2023-01-13T02:00:00+01:00"
      ],
      [
        2.65,
        "2023-01-13T03:00:00+01:00"
      ],
      [
        3.35,
        "2023-01-13T04:00:00+01:00"
      ],
      [
        25.26,
        "2023-01-13T05:00:00+01:00"
      ],
      [
        54.740002,
        "2023-01-13T06:00:00+01:00"
      ],
      [
        87.879997,
        "2023-01-13T07:00:00+01:00"
      ],
      [
        105.949997,
        "2023-01-13T08:00:00+01:00"
      ],
      [
        100.639999,
        "2023-01-13T09:00:00+01:00"
      ],
      [
        94.849998,
        "2023-01-13T10:00:00+01:00"
      ],
      [
        84.93,
        "2023-01-13T11:00:00+01:00"
      ],
      [
        76.529999,
        "2023-01-13T12:00:00+01:00"
      ],
      [
        70.239998,
        "2023-01-13T13:00:00+01:00"
      ],
      [
        73.550003,
        "2023-01-13T14:00:00+01:00"
      ],
      [
        79.849998,
        "2023-01-13T15:00:00+01:00"
      ],
      [
        85.309998,
        "2023-01-13T16:00:00+01:00"
      ],
      [
        96.900002,
        "2023-01-13T17:00:00+01:00"
      ],
      [
        96.970001,
        "2023-01-13T18:00:00+01:00"
      ],
      [
        95.910004,
        "2023-01-13T19:00:00+01:00"
      ],
      [
        84.940002,
        "2023-01-13T20:00:00+01:00"
      ],
      [
        76.889999,
        "2023-01-13T21:00:00+01:00"
      ],
      [
        76.510002,
        "2023-01-13T22:00:00+01:00"
      ],
      [
        68.300003,
        "2023-01-13T23:00:00+01:00"
      ]
    ],
    "tomorrow": [
      [
        0.436,
        "2023-01-14T00:00:00+01:00"
      ],
      [
        0.519,
        "2023-01-14T01:00:00+01:00"
      ],
      [
        0.612,
        "2023-01-14T02:00:00+01:00"
      ],
      [
        0.58,
        "2023-01-14T03:00:00+01:00"
      ],
      [
        0.575,
        "2023-01-14T04:00:00+01:00"
      ],
      [
        0.575,
        "2023-01-14T05:00:00+01:00"
      ],
      [
        0.616,
        "2023-01-14T06:00:00+01:00"
      ],
      [
        0.693,
        "2023-01-14T07:00:00+01:00"
      ],
      [
        0.695,
        "2023-01-14T08:00:00+01:00"
      ],
      [
        0.726,
        "2023-01-14T09:00:00+01:00"
      ],
      [
        0.817,
        "2023-01-14T10:00:00+01:00"
      ],
      [
        0.806,
        "2023-01-14T11:00:00+01:00"
      ],
      [
        0.805,
        "2023-01-14T12:00:00+01:00"
      ],
      [
        0.78,
        "2023-01-14T13:00:00+01:00"
      ],
      [
        0.589,
        "2023-01-14T14:00:00+01:00"
      ],
      [
        0.382,
        "2023-01-14T15:00:00+01:00"
      ],
      [
        0.281,
        "2023-01-14T16:00:00+01:00"
      ],
      [
        0.3,
        "2023-01-14T17:00:00+01:00"
      ],
      [
        0.324,
        "2023-01-14T18:00:00+01:00"
      ],
      [
        0.26,
        "2023-01-14T19:00:00+01:00"
      ],
      [
        0.281,
        "2023-01-14T20:00:00+01:00"
      ],
      [
        0.281,
        "2023-01-14T21:00:00+01:00"
      ],
      [
        0.252,
        "2023-01-14T22:00:00+01:00"
      ],
      [
        0.245,
        "2023-01-14T23:00:00+01:00"
      ]
    ],
    "tomorrow_calculated": true,
    "api_tomorrow": [
      [
        25.68,
        "2023-01-14T00:00:00+01:00"
      ],
      [
        34.619999,
        "2023-01-14T01:00:00+01:00"
      ],
      [
        44.700001,
        "2023-01-14T02:00:00+01:00"
      ],
      [
        41.23,
        "2023-01-14T03:00:00+01:00"
      ],
      [
        40.700001,
        "2023-01-14T04:00:00+01:00"
      ],
      [
        40.68,
        "2023-01-14T05:00:00+01:00"
      ],
      [
        45.099998,
        "2023-01-14T06:00:00+01:00"
      ],
      [
        53.400002,
        "2023-01-14T07:00:00+01:00"
      ],
      [
        53.630001,
        "2023-01-14T08:00:00+01:00"
      ],
      [
        56.889999,
        "2023-01-14T09:00:00+01:00"
      ],
      [
        66.720001,
        "2023-01-14T10:00:00+01:00"
      ],
      [
        65.559998,
        "2023-01-14T11:00:00+01:00"
      ],
      [
        65.389999,
        "2023-01-14T12:00:00+01:00"
      ],
      [
        62.689999,
        "2023-01-14T13:00:00+01:00"
      ],
      [
        42.150002,
        "2023-01-14T14:00:00+01:00"
      ],
      [
        19.92,
        "2023-01-14T15:00:00+01:00"
      ],
      [
        9.04,
        "2023-01-14T16:00:00+01:00"
      ],
      [
        11.04,
        "2023-01-14T17:00:00+01:00"
      ],
      [
        13.69,
        "2023-01-14T18:00:00+01:00"
      ],
      [
        6.84,
        "2023-01-14T19:00:00+01:00"
      ],
      [
        9.03,
        "2023-01-14T20:00:00+01:00"
      ],
      [
        9.07,
        "2023-01-14T21:00:00+01:00"
      ],
      [
        5.9,
        "2023-01-14T22:00:00+01:00"
      ],
      [
        5.19,
        "2023-01-14T23:00:00+01:00"
      ]
    ],
    "predictions": null,
    "api_predictions": null,
    "tariff_data": {
      "additional_tariffs": {
        "transmissions_net_tarif": 0.058,
        "system_tarif": 0.054,
        "el_afgift": 0.008
      },
      "tariffs": {}
    },
    "next_update": "13:16:23",
    "data_source": "Energi Data Service",
    "home_assistant_tz": "Europe/Copenhagen",
    "home_assistant_currency": "DKK"
  }
}

```
